# Generated by Django 4.1.7 on 2023-02-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '產品分類', 'verbose_name_plural': '產品分類'},
        ),
    ]
