# Generated by Django 4.1.7 on 2023-03-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
